[theme]
base = "light"
primaryColor = "#7E22CE"
backgroundColor = "#FAFAFE"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
fileWatcherType = "none"
